### ISSUE TITLE
sftp permission denied

### ISSUE THREAD

**Issue by rbtrary** [AsavarTzeth/docker-sftp#3]
Not understanding why this permission denied issue with default /sftp1 user please?

$ sftp -P 2222 sftp1@localhost
=================================================================================
Welcome to your new sftp container!

To get the passwords, on the docker host system run this:
docker cp some-container:/sftp_pass .

For more information, see the official README.md
Link: http://registry.hub.docker.com/u/asavartzeth/sftp/
Link: http://github.com/AsavarTzeth/docker-sftp/
=================================================================================
sftp1@localhost's password: 
Connected to localhost.
sftp> put test.txt
Uploading test.txt to /sftp1/test.txt
remote open("/sftp1/test.txt"): Permission denied
sftp>

**Comment by rbtrary** [comment]
Fixed issue seemed to be permission at higher level.

**Comment by AsavarTzeth** [comment]
In case of anyone else asking. Any permission errors you have has nothing to do with the container. It is the responsibility of the admin to use volumes to link the container to wherever you wan to upload/download files. You then have to make sure users/groups are mapped to the same uid/gid.

In the end it all depends on your setup.

What I have failed to do though, was finishing and commiting my improved (example based) user documentation, which cleanly explains how to set things up for this to work perfectly.

**Comment by AsavarTzeth** [comment]
Shorter summary: It is never wise to store the data inside your container, since that would be lost on upgrade. Because of this, I do not support this. If you do store data properly (externaly), then really I cannot assume anything, right? It up to you.
