### ISSUE TITLE
Users don't have write privileges to their own folder

### ISSUE THREAD

**Issue by remo1024** [AsavarTzeth/docker-sftp#6]
I am new to docker and your image, so forgive my (possible) ignorance.  I ran your image and was able to log into the SFTP server, but discovered the user did not have write privileges.  I noticed the following line in /entrypoint.sh:
&nbsp;&nbsp;chown root:root $SFTP_CHROOT/$user
which I changed to:
&nbsp;&nbsp;chown $user:root $SFTP_CHROOT/$user

This allows the user to write to their own folder.  Was there a reason that you made the owner of the users folder root?  Perhaps you only wanted a read-only container?  If so, then it is my belief the folder should be owned by the user and the permissions of the folder should remove write privileges.  Am I missing something obvious?

Cheers,
Rich

**Comment by AsavarTzeth** [comment]
Yes data should not be stored in the container. That aspect of Docker is really bad; it is easy for beginners to make that mistake. Remember if you cannot throw away a container at any time without losing anything of value, you are doing it wrong.

The correct way to do it is using environment variables and either storing the data on the host or a data container. This has been in the Docker documentation as well as my own for a long time.

**Comment by AsavarTzeth** [comment]
At the same time. I feel obligated to inform you that this container (like most) really does not get the maintenance it needs. It should still be fine to use for personal use, learning, playing, or as an example Docker image though.

**Comment by remo1024** [comment]
Thanks for your feedback!  Yes, I agree the documentation about the what/why/how of using data containers in Docker is weak in general.  Your documentation got me pointed in the right direction, though.

My use for your SFTP container is to learn and eventually build out a test-only SFTP container.  Any data would be for testing and could be thrown away.  Regardless, I still plan on using a data container as part of my learning process to accomplish this.

**Comment by AsavarTzeth** [comment]
Glad to be able to help. You are not the first to be confused with my 
container image. No container is a like and it can be difficult to make 
it easy to use, secure, simple and follow all best practices at the 
same time.

You seem well informed though and on the right path. I wish you good 
luck in your future Docker endevours.

Wed 12/30/2015 klockan 19:21 +0100 skrev remo1024 
<notifications@github.com>:
