### ISSUE TITLE
Connection closes as soon as I authenticate

### ISSUE THREAD

**Issue by Bre77** [AsavarTzeth/docker-sftp#7]
I have the container setup with variables changing the username and password. When I connect to it using the correct username and password, the connection is closed by the server immediately. Incorrect user names and passwords throw messages about being incorrect, its only when everything is correct that the connection is dropped.

Accepted password for downloader from 192.168.1.4 port 54111 ssh2
bad ownership or modes for chroot directory component "/"
Accepted password for downloader from 192.168.1.4 port 54118 ssh2
bad ownership or modes for chroot directory component "/"
Address x.x.x.x maps to x.com, but this does not map back to the address - POSSIBLE BREAK-IN ATTEMPT!
Accepted password for downloader from x.x.x.x port 3287 ssh2
bad ownership or modes for chroot directory component "/"
Address x.x.x.x maps to x.com, but this does not map back to the address - POSSIBLE BREAK-IN ATTEMPT!
Accepted password for downloader from x.x.x.x port 3292 ssh2
bad ownership or modes for chroot directory component "/"

**Comment by AsavarTzeth** [comment]
You would have to provide me more information for me to be able to help. I have not tested this container image regularly in a long time, but it should still work.

Some questions:
- Are you passing any other environment variables to docker? If so, which ones?
- What documentation did you read prior to this?
- I am also curious if you built this image yourself, or if not, where did you get it?

I must also inform you that this project is not actively being maintained. It is mostly left for archiving and academic purposes. I updated the description to reflect this.

Still, If I have time and you provide enough information, I might still be able to help you.
