### ISSUE TITLE
Authaniation Problem

### ISSUE THREAD

**Issue by pratapnanda** [AsavarTzeth/docker-sftp#8]
Hi 
I have created a docker container using below command

docker run --name SFTPmock -v /mySftpVolume:/home/test123/upload -e SFTP_USER=test123 -e SFTP_PASS=abc123 -p 2222:22 -d asavartzeth/sftp

when i try to connect from other container using below command 
[root@355f3fbc7c97 /]# sftp test123:abc123@10.200.4.154:22/upload
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Couldn't read packet: Connection reset by peer

telnet is working
[root@355f3fbc7c97 /]# telnet 10.200.4.154 22
Trying 10.200.4.154...
Connected to 10.200.4.154.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.4

**Comment by AsavarTzeth** [comment]
See the repository description "This project isn't being actively maintained. That also means it is not supported."
